DROP TABLE pro_marca;

CREATE TABLE pro_marca (
	cod int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar (30) NOT NULL,
	ativo bool NOT NULL,
	fornecedor_principal varchar (150) NULL,
	data_inicial timestamp NULL,
	CONSTRAINT pro_marca_pk PRIMARY KEY (cod)
);